### ISSUE TITLE
no puedo instalar en el composer.json

### ISSUE THREAD

**Issue by DarknesChaos** [alejogutierrez/laravel-payu#1]
buenos dias.

al intentar instalar la libreria me manda este error:
C:\xampp\htdocs\corner\portal>composer require alexo/laravel-payu
Using version [32m^1.0[39m for [32malexo/laravel-payu[39m
[32m./composer.json has been updated[39m
[32mLoading composer repositories with package information[39m
[32mUpdating dependencies (including require-dev)[39m
[37;41mYour requirements could not be resolved to an installable set of packages.[39;49m

  Problem 1
    - Conclusion: don't install alexo/laravel-payu 1.0.3
    - Conclusion: don't install alexo/laravel-payu 1.0.2
    - Conclusion: don't install alexo/laravel-payu 1.0.1
    - Conclusion: remove symfony/translation v2.7.27
    - Installation request for alexo/laravel-payu ^1.0 -> satisfiable by alexo/laravel-payu[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - Conclusion: don't install symfony/translation v2.7.27
    - alexo/laravel-payu 1.0.0 requires symfony/translation ~3.1.5 -> satisfiable by symfony/translation[v3.1.10, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9].
    - Can only install one of: symfony/translation[v3.1.10, v2.7.27].
    - Can only install one of: symfony/translation[v3.1.5, v2.7.27].
    - Can only install one of: symfony/translation[v3.1.6, v2.7.27].
    - Can only install one of: symfony/translation[v3.1.7, v2.7.27].
    - Can only install one of: symfony/translation[v3.1.8, v2.7.27].
    - Can only install one of: symfony/translation[v3.1.9, v2.7.27].
    - Installation request for symfony/translation (locked at v2.7.27) -> satisfiable by symfony/translation[v2.7.27].

[37;41mInstallation failed, reverting ./composer.json to its original content.[39;49m

estoy usando laravel 5.1, no se cual sea el problema

**Comment by alejogutierrez** [comment]
Hola 
No he utilizado la librería con esa versión de Laravel, he probado desde la 5.3, aunque no creo que ese sea el problema.
Revisa si el servidor local xampp tiene la version php: >=5.5.9, y también instalando la librería en un proyecto en limpio para descartar.

**Comment by DarknesChaos** [comment]
Hola.

Revise el servidor local de xampp tiene la versión php:>=5.6.23 y ya probé con un proyecto limpio y me arroja el mismo error

**Comment by alejogutierrez** [comment]
Hola acabo de actualizar el composer para que funcione con las versiones anteriores de symfony translation, ese era el problema.
Gracias por informar espero que te sirva.
