### ISSUE TITLE
PayUException: El medio de pago [VISA] no está soportado

### ISSUE THREAD

**Issue by angelrod** [alejogutierrez/laravel-payu#4]
Estuve en modo test durante bastante tiempo, todo funciona bien con tarjetas Visa y Mastercard de pruebas. Al momento de pasar a producción obtengo el siguiente error:

PayUException: El medio de pago [VISA] no está soportado in /var/www/petpediadev/vendor/alexo/laravel-payu/sdk/lib/PayU/util/PayUApiServiceUtil.php:67

**.env en producción:**
```
APP_ENV=staging
PAYU_ON_TESTING=false
PAYU_MERCHANT_ID=****
PAYU_API_LOGIN=*************
PAYU_API_KEY=*****************
PAYU_ACCOUNT_ID=*********
PAYU_COUNTRY=PA
PSE_REDIRECT_URL=

```
**.env en test:**
```
PAYU_ON_TESTING=true
PAYU_MERCHANT_ID=508029
PAYU_API_LOGIN=pRRXKOl8ikMmt9u
PAYU_API_KEY=4Vj8eK4rloUd272L48hsrarnUA
PAYU_ACCOUNT_ID=512326
PAYU_COUNTRY=PA
PSE_REDIRECT_URL=your-pse-redirect-url
```

Esta es la data que estoy enviando:

```
$data = [
            \PayUParameters::REFERENCE_CODE => $orden_nr,
            \PayUParameters::DESCRIPTION => "Servicio PETpedia",
            \PayUParameters::VALUE => $monto,
            \PayUParameters::CURRENCY => "USD",
            \PayUParameters::PAYER_NAME => $nombre,
            \PayUParameters::PAYER_EMAIL => $user->email,
            \PayUParameters::PAYER_CONTACT_PHONE => $user->celular,
         
            \PayUParameters::CREDIT_CARD_NUMBER => $tarjeta,
            \PayUParameters::CREDIT_CARD_EXPIRATION_DATE => $fecha,
            \PayUParameters::CREDIT_CARD_SECURITY_CODE=> $cvv,
            \PayUParameters::PAYMENT_METHOD => $tipo,
            \PayUParameters::INSTALLMENTS_NUMBER => "1",                    
        ];
```

¿Alguna sugerencia?.
 Muchas gracias de antemano!!

**Comment by angelrod** [comment]
Luego de realizar muchísimas pruebas y varias charlas con el soporte técnico de PayU, el error fue por problemas administrativos en la configuración de la cuenta, nada que ver con el código.

**Comment by alejogutierrez** [comment]
Gracias por confirmar

**Comment by jmanzo** [comment]
@alejogutierrez pero exactamente cual fue el valor administrativo que tuviste que modificar para que funcionara?
