### ISSUE TITLE
No es compatible con Carbon 2

### ISSUE THREAD

**Issue by Samanathor** [alejogutierrez/laravel-payu#5]
Hola como estás Alejo pasa que quiero instalarlo pero no es compatible con Carbon 2, pero Laravel 6 y 7 solo usan Carbon 2

**Comment by alejogutierrez** [comment]
Hola gracias por informar, este paquete lo trabaje hace mucho y tanto Laravel como las dependencias han cambiado bastante. Lanzaré una nueva versión pronto, mientras tanto voy publicar esta semana la actualización de _Carbon_ a la última versión. Por lo pronto te recomiendo que uses la librería como una dependencia local y actualices el _Carbon_ en ese entorno local.

**Comment by Samanathor** [comment]
Hola, gracias por contestar, mira que me resigne, no sé si sigue funcionando o no, pero no bota ningun error, o sea simplemente no responde, entonces se me imposibilito usarlo, estoy usando la api, pues todavía sigo configurando todo, espero lo revises con Laravel 6, 7

**Comment by Samanathor** [comment]
E igual si necesitas algún tipo de ayuda me encantaría colaborarte.

**Comment by alejogutierrez** [comment]
Se quitó la dependencia de Carbon que estaba siendo usada para adicionar a unas fechas, es decir un cañon para una mosca, ya puedes instalar la librería.
